# Generated by Django 5.1.1 on 2024-09-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0002_alter_customuser_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido1', models.CharField(max_length=255)),
                ('apellido2', models.CharField(blank=True, max_length=255)),
                ('tpidentificacion', models.CharField(choices=[('', 'Seleccione un el tipo de Identificación'), ('CC', 'Cedula de Ciudadania'), ('CE', 'Cedula de Extrangeria'), ('TI', 'Tarjeta de Identidad'), ('RC', 'Registro Civil'), ('P', 'Pasaporte')], default='', max_length=10)),
                ('numeroidentificacion', models.CharField(max_length=50)),
                ('fechanacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('Femenino', 'Femenino'), ('Maculino', 'Maculino'), ('Otro', 'Otro')], max_length=10, verbose_name='Sexo biológico')),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
