# Generated by Django 5.1.1 on 2024-09-24 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0003_pacientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_orden', models.DateField()),
                ('codigo_documento', models.CharField(max_length=100)),
                ('numero_orden', models.CharField(max_length=20)),
                ('pacientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultados.pacientes')),
            ],
            options={
                'ordering': ['-fecha_orden'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=100)),
                ('procedimiento', models.CharField(max_length=100)),
                ('resultado', models.CharField(max_length=100)),
                ('orden_laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='resultados.ordenlaboratorio')),
            ],
        ),
    ]
