# Generated by Django 5.1.1 on 2024-09-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0006_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoprueba',
            name='grupo',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('B+', 'B+'), ('B-', 'B-')], max_length=100),
        ),
    ]
