# Generated by Django 5.1.1 on 2024-09-25 19:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0008_rename_grupo_resultadoprueba_grupo_sanguineo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoprueba',
            name='fecha_resultado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
