# Generated by Django 5.1.1 on 2024-09-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0009_resultadoprueba_fecha_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='grupo_sanguineo',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('B+', 'B+'), ('B-', 'B-')], default='O+', max_length=100),
            preserve_default=False,
        ),
    ]
